sudo: required
dist: xenial

language: php
php:
  - 'master'
  - '7.3.0RC1'
  - '7.2'
  - '7.1'

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

addons:
  apt:
    packages:
      - libzip4

services:
  - redis-server

git:
  depth: 1

branches:
  only:
    - master
    - development

cache:
  apt: true
  ccache: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache

env:
  global:
  - REDIS_HOST="127.0.0.1"
  - REDIS_PORT="6379"
  - REDIS_TIMEOUT="0.0"
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
  - ulimit -c unlimited -S || true
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  - phpenv which php
  - php -v
  - php -m | grep -e 'json\|pcntl\|posix\|redis\|sockets\|pcre'
  - composer diagnose || true
  - chmod +x ./qlessd

script:
  - ./qlessd --help
  - ./vendor/bin/phpunit --disallow-test-output

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then (bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"); fi;

notifications:
  email: false

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env: PHPStan
      script:
        - ./vendor/bin/phpstan analyse -l max src
    - stage: Static Code Analysis
      php: 7.2
      env: PHP_CodeSniffer
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - ./vendor/bin/phpcs
    - stage: Benchmark
      php: 7.2
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - chmod +x ./tests/simple-bench
        - ./tests/simple-bench --port $REDIS_PORT --host $REDIS_HOST

