sudo: false
dist: trusty

language: php

php:
  - '7.1'
  - '7.2'
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: master

services:
  - redis-server

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/pear
env:
  global:
  - REDIS_HOST="127.0.0.1"
  - REDIS_PORT="6379"
  - REDIS_TIMEOUT="0.0"
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
  - ulimit -c unlimited -S || true
  - bash tests/ci/pear_setup.sh
  - phpenv config-add $TRAVIS_BUILD_DIR/tests/ci/ci.ini

install:
  - composer install $DEFAULT_COMPOSER_FLAGS
  - chmod +x ./tests/simple-bench
  - chmod +x ./qlessd

before_script:
  - phpenv which php
  - php -m | grep -e 'json\|pcntl\|posix\|redis\|sockets\|pcre'
  - ./qlessd --help
  - composer diagnose || true

script:
  - ./vendor/bin/phpunit --disallow-test-output

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then (bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"); fi;

notifications:
  email: false

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env: PHPStan
      script:
        - ./vendor/bin/phpstan analyse -l max src
    - stage: Static Code Analysis
      php: 7.2
      env: PHP_CodeSniffer
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - ./vendor/bin/phpcs
    - stage: Benchmark
      php: 7.2
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - ./tests/simple-bench --port $REDIS_PORT --host $REDIS_HOST
